# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: make-fmt
        name: make fmt
        entry: make
        args: [fmt]
        language: system
        pass_filenames: false
      - id: make-check
        name: make check
        entry: make
        args: [check]
        language: system
        pass_filenames: false
